#!/usr/bin/env python3
"""Fragments the assistant needs to say command results in its own voice.

A result like "Сейчас 14 часов 5 минут" is half known in advance: the shape is fixed, the
numbers are not, and generating every combination is out of the question. It is therefore
generated in pieces ("Сейчас 14 часов" + "5 минут") that the assistant plays back to back.

Each line is `text as the assistant writes it | how to say it`, because the commands emit
digits ("Заряд 82 процентов") while speech needs words in the right case ("Заряд
восемьдесят два процента").

    ./fragments-ru.py > fragments-ru.txt
"""

UNITS = ["ноль", "один", "два", "три", "четыре", "пять", "шесть", "семь", "восемь",
         "девять", "десять", "одиннадцать", "двенадцать", "тринадцать", "четырнадцать",
         "пятнадцать", "шестнадцать", "семнадцать", "восемнадцать", "девятнадцать"]

TENS = {2: "двадцать", 3: "тридцать", 4: "сорок", 5: "пятьдесят",
        6: "шестьдесят", 7: "семьдесят", 8: "восемьдесят", 9: "девяносто"}

FEMININE = {"один": "одна", "два": "две"}

ORDINALS = ["", "первое", "второе", "третье", "четвёртое", "пятое", "шестое", "седьмое",
            "восьмое", "девятое", "десятое", "одиннадцатое", "двенадцатое", "тринадцатое",
            "четырнадцатое", "пятнадцатое", "шестнадцатое", "семнадцатое",
            "восемнадцатое", "девятнадцатое", "двадцатое"]

ORDINAL_TENS = {2: "двадцать", 3: "тридцать"}
ORDINAL_ROUND = {30: "тридцатое"}

MONTHS = ["января", "февраля", "марта", "апреля", "мая", "июня",
          "июля", "августа", "сентября", "октября", "ноября", "декабря"]


def number(value, feminine=False):
    if value == 100:
        return "сто"
    if value < 20:
        word = UNITS[value]
        return FEMININE.get(word, word) if feminine else word

    tens, unit = divmod(value, 10)
    return TENS[tens] if unit == 0 else f"{TENS[tens]} {number(unit, feminine)}"


def ordinal(value):
    if value <= 20:
        return ORDINALS[value]
    if value in ORDINAL_ROUND:
        return ORDINAL_ROUND[value]

    tens, unit = divmod(value, 10)
    return f"{ORDINAL_TENS[tens]} {ORDINALS[unit]}"


# Russian counts in three forms: 1 процент, 2 процента, 5 процентов.
def plural(value, one, few, many):
    if value % 100 in (11, 12, 13, 14):
        return many
    return {1: one, 2: few, 3: few, 4: few}.get(value % 10, many)


def fragments():
    yield "# Generated by fragments-ru.py - pieces of the results commands speak."
    yield "# `written by the command | said out loud`"

    # time.lua: "Сейчас %d часов %d минут"
    yield "\n# time"
    for hour in range(24):
        yield (f"Сейчас {hour} часов | Сейчас {number(hour)} "
               f"{plural(hour, 'час', 'часа', 'часов')}")
    for minute in range(60):
        yield (f"{minute} минут | {number(minute, feminine=True)} "
               f"{plural(minute, 'минута', 'минуты', 'минут')}")

    # date.lua: "Сегодня %d <месяц>"
    yield "\n# date"
    for day in range(1, 32):
        yield f"Сегодня {day} | Сегодня {ordinal(day)}"
    for month in MONTHS:
        yield month

    # battery.lua: "Заряд %d процентов" and ", питание от сети"
    yield "\n# battery"
    for percent in range(101):
        yield (f"Заряд {percent} процентов | Заряд {number(percent)} "
               f"{plural(percent, 'процент', 'процента', 'процентов')}")
    yield "питание от сети"


if __name__ == "__main__":
    print("\n".join(fragments()))
