#!/usr/bin/env python3
"""Speak arbitrary text in a voice pack's voice.

The voice packs are a few short recordings, so nothing in them can say a sentence that was
not recorded. F5-TTS clones a voice from a single reference clip without any training, which
is enough to read out answers and command results in the assistant's own voice.

Two modes:
  --phrases FILE --out DIR   generate a phrase bank ahead of time (no runtime dependency)
  --serve                    keep the model loaded and synthesize on demand, one JSON
                             request per line on stdin: {"text": "...", "out": "/tmp/x.wav"}
"""

import argparse
import json
import os
import sys
import time

MODEL_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "model")


def log(*args):
    print(*args, file=sys.stderr, flush=True)


def load(device, nfe_step):
    from f5_tts.api import F5TTS

    started = time.time()
    tts = F5TTS(
        model="F5TTS_v1_Base",
        ckpt_file=os.path.join(MODEL_DIR, "model.safetensors"),
        vocab_file=os.path.join(MODEL_DIR, "vocab.txt"),
        device=device,
    )
    log(f"model loaded in {time.time() - started:.1f}s (device={device}, nfe_step={nfe_step})")
    return tts


def synthesize(tts, reference, reference_text, text, out_path, nfe_step):
    import soundfile as sf

    started = time.time()
    wav, sample_rate, _ = tts.infer(
        ref_file=reference,
        ref_text=reference_text,
        gen_text=text,
        nfe_step=nfe_step,
        remove_silence=False,
    )
    sf.write(out_path, wav, sample_rate)
    return len(wav) / sample_rate, time.time() - started


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--reference", required=True, help="reference recording (wav/mp3) of the voice")
    parser.add_argument("--reference-text", required=True, help="what is said in the reference recording")
    parser.add_argument("--phrases", help="file with one phrase per line")
    parser.add_argument("--out", help="output directory for --phrases")
    parser.add_argument("--serve", action="store_true", help="read requests from stdin")
    parser.add_argument("--device", default="mps" if sys.platform == "darwin" else "cpu")
    parser.add_argument("--nfe-step", type=int, default=16,
                        help="diffusion steps: 32 best quality, 16 balanced, 8 fastest")
    args = parser.parse_args()

    tts = load(args.device, args.nfe_step)

    if args.serve:
        # one request per line; the model stays loaded between them
        print(json.dumps({"ready": True}), flush=True)
        for line in sys.stdin:
            line = line.strip()
            if not line:
                continue
            try:
                request = json.loads(line)
                duration, took = synthesize(
                    tts, args.reference, args.reference_text,
                    request["text"], request["out"], args.nfe_step,
                )
                print(json.dumps({"out": request["out"], "duration": duration, "took": took}), flush=True)
            except Exception as error:  # a bad request must not kill the server
                print(json.dumps({"error": str(error)}), flush=True)
        return

    if not args.phrases or not args.out:
        parser.error("either --serve or --phrases with --out is required")

    os.makedirs(args.out, exist_ok=True)
    manifest = {}

    with open(args.phrases, encoding="utf-8") as handle:
        phrases = [line.strip() for line in handle if line.strip() and not line.startswith("#")]

    for index, phrase in enumerate(phrases, start=1):
        name = f"phrase{index:03d}.wav"
        duration, took = synthesize(
            tts, args.reference, args.reference_text, phrase,
            os.path.join(args.out, name), args.nfe_step,
        )
        manifest[phrase] = name
        log(f"[{index}/{len(phrases)}] {phrase[:60]!r} -> {name} ({duration:.1f}s audio in {took:.1f}s)")

    # the assistant looks phrases up by their text
    with open(os.path.join(args.out, "phrases.toml"), "w", encoding="utf-8") as handle:
        handle.write("# Generated by scripts/voice-clone/synth.py - phrases spoken in this pack's voice.\n")
        handle.write("# The assistant plays these instead of synthesizing, so they cost nothing at runtime.\n\n")
        for phrase, name in manifest.items():
            escaped = phrase.replace('"', '\\"')
            handle.write(f'"{escaped}" = "{name}"\n')

    log(f"done: {len(manifest)} phrases in {args.out}")


if __name__ == "__main__":
    main()
