[package]
name = "jarvis-gui"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
jarvis-core = { path = "../jarvis-core", default-features = false }
tauri = { version = "2", features = [] } # v1: "shell-open", "dialog-message", "path-all"
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"

sysinfo.workspace = true

once_cell.workspace = true
log.workspace = true
simple-log = "2.4"
serde.workspace = true
serde_json.workspace = true
platform-dirs.workspace = true
parking_lot.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
