// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IpcAction = { "action": "auth", token: string, } | { "action": "stop" } | { "action": "reload_commands" } | { "action": "apply_settings" } | { "action": "ping" } | { "action": "set_muted", muted: boolean, } | { "action": "text_command", text: string, };

export type IpcEvent = { "event": "wake_word_detected" } | { "event": "listening" } | { "event": "speech_recognized", text: string, } | { "event": "command_executed", id: string, success: boolean, } | { "event": "idle" } | { "event": "error", message: string, } | { "event": "started", protocol: number, } | { "event": "stopping" } | { "event": "pong" } | { "event": "reveal_window" } | { "event": "muted", muted: boolean, } | { "event": "commands_reloaded", count: number, } | { "event": "settings_applied", changed: Array<string>, } | { "event": "ai_answer", question: string, answer: string, };
